# Generated by Django 3.1.6 on 2021-02-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0003_auto_20210213_1917'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/')),
            ],
        ),
    ]
