# Generated by Django 3.1.6 on 2021-02-15 20:10

from django.db import migrations, models
import django.db.models.deletion
import portfolio_projects.models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='is_draft',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='image',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio_projects.article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to=portfolio_projects.models.get_image_path),
        ),
    ]
