# Generated by Django 3.1.6 on 2021-02-15 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0006_image_folder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
        migrations.RemoveField(
            model_name='image',
            name='folder',
        ),
    ]
