# Generated by Django 3.1.7 on 2021-03-15 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_projects', '0007_auto_20210215_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='article',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='portfolio_projects.article'),
            preserve_default=False,
        ),
    ]
